[package]
name = "dhd_core"
version = "0.1.0"
authors = ["Eric Mark Martin <ericmarkmartin@gmail.com>"]
edition = "2018"

[features]
graphql = ["juniper"]

[dependencies]
juniper = { version = "0.14.2", optional = true }
difference = "2.0.0"
itertools = "0.9.0"
